project:
  type: website
  output-dir: docs

website:
  title: "Alape Aniruddha"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



